version: 2

sources:
  - name: pipedrive_crm_raw
    description: >
      Raw data ingested from Pipedrive CRM. The 'loaded_at_field' uses a business
      timestamp (e.g., change_time) as a necessary proxy for pipeline freshness,
      as a true ingestion timestamp is not available.
    database: postgres
    schema: public # Matches the required schema for reading
    tags: ["source_data", "pipedrive_crm_raw"]

    tables:
      # ====================================================================
      # 1. EVENT TABLES (High Volume / Needs Freshness Check)
      # ====================================================================
      - name: deal_changes
        # PROXY FRESHNESS: Using the time the deal last changed as a freshness indicator.
        loaded_at_field: change_time 
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              min_value: 1 # Ensure at least 1 change event is loaded daily
              group_by: [cast(change_time as date)] # Group by the available business date
        columns:
          - name: deal_id
            tests:
              - not_null
          - name: change_time
            tests:
              - not_null
          - name: changed_field_key
            tests:
              - not_null

      - name: activity
        # PROXY FRESHNESS: Using the time the activity is due/logged.
        loaded_at_field: due_to 
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 3, period: day}
        columns:
          - name: activity_id
            tests:
              - not_null
          - name: deal_id
            tests:
              - not_null
          - name: done
            tests:
              - not_null

      - name: users
        # PROXY FRESHNESS: Using the time the user profile was last modified.
        loaded_at_field: modified 
        freshness:
          warn_after: {count: 7, period: day} # Users change less often
          error_after: {count: 14, period: day}
        columns:
          - name: id
            tests:
              - not_null
              
      # ====================================================================
      # 2. STATIC LOOKUP TABLES (No freshness/volume tests needed)
      # ====================================================================
      - name: activity_types
        columns:
          - name: id
            tests:
              - not_null

      - name: stages
        columns:
          - name: stage_id
            tests:
              - not_null

      - name: fields
        columns:
          - name: id
            tests:
              - not_null